### ISSUE TITLE
ฉันน่ารักมาก

### ISSUE THREAD

**Issue by mocha-1** [iirinz/gitegco#1]
เดบิ้วเป็นมัมหมี นจก

**Comment by iirinz** [comment]
problem solve 
เป็นคนที่ถูกรักให้ได้ก่อน

**Comment by mocha-1** [comment]
ขอบคุณที่สอนฉันให้รู้จักความรัก

ฉันตายโดยปราศจากคนที่รักฉัน แต่ฉันก็อุ่นใจที่ฉันมีคนที่ฉันรัก
